Repository Group-47-Capstone-2019/Immersive-Web-VR-AR, pull requests merged in 2019-01, with the labels that each got.

#33 Page content+styling
  src/index.html
  src/scripts/index.js
  src/styles/style.css
Labels: wip

#35 Update CSS
  src/index.html
Labels: wip

#39 Room mesh initial completion
  src/images/wall.png
  src/scripts/index.js
Labels: Feature, Three, sprint 1

#40 Feat/browser history
  now.json
  src/index.html
  src/scripts/index.js
  src/scripts/links.js
  src/scripts/old.js
  src/scripts/renderer/camera.js
  src/scripts/renderer/canvas.js
  src/scripts/renderer/index.js
  src/scripts/router.js
  src/scripts/scenes/home.js
  src/scripts/scenes/planets.js
  src/styles/style.css
Labels: sprint 1
